CREATE TABLE "DictWord" (
    "DictWordID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "PojUnicode" TEXT,
    "PojInput" TEXT,
    "KipUnicode" TEXT,
    "KipInput" TEXT,
    "HoaBun" TEXT,
    "EngBun" TEXT,
    "AudioUrl" TEXT,

    CONSTRAINT "DictWord_pkey" PRIMARY KEY ("DictWordID")
);

CREATE INDEX "DictWord_HoaBun_idx" ON "DictWord"("HoaBun");
CREATE INDEX "DictWord_EngBun_idx" ON "DictWord"("EngBun");
